#!/usr/bin/env python3
"""
services/satellites/install-piper.py
-----------------------------------
Install the OPTIONAL Piper neural voice for the Satellites pass alert.

Without this, pass alerts still speak: the voice ladder in common/js/sat-alerts.js
falls back to espeak-ng's female variant (+Steph2), which install-voice.py already
put on the box. This step swaps that formant synth for a voice trained on recorded
speech — the difference between "intelligible" and "pleasant" when the operator is
across the room.

How it reaches the browser: Chromium's Web Speech API can only see voices that
speech-dispatcher publishes, and speech-dispatcher cannot load an .onnx. So this
installs a GENERIC output module — a config file telling speech-dispatcher to pipe
text through the piper binary and play the raw audio it emits. Chromium then lists
it as an ordinary voice, and the page's ladder prefers it by name.

Offline-first: reads the engine tarball and the voice model from the bundle
(services/satellites/packages/satellites-piper/, manifest features
'satellites-piper' + 'satellites-piper-voice', both filled by
create-oasis-offline.py on the operator's connected build machine). There is NO
online fallback — OASIS does not download a voice model at install time, by design.

Idempotent and safe to re-run: an existing engine of the same version is left
alone, and the module config is rewritten from scratch each run so a hand-edit
never accumulates.

Usage:
  python3 services/satellites/install-piper.py
  python3 services/satellites/install-piper.py --uninstall
"""

import argparse
import json
import os
import platform
import shutil
import sys
import tarfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO_ROOT)
import common.manifest as M  # noqa: E402
from common.oasis_lib import _hr, _ok, _info, _warn, _run  # noqa: E402

FEATURE = "satellites-piper"
VOICE_FEATURE = "satellites-piper-voice"

# Engine and voice live together, root-owned and world-readable: speech-dispatcher
# runs as the desktop user, not as root, and must be able to read both.
INSTALL_DIR = "/opt/oasis-piper"
MODULE_NAME = "oasis-piper"
SPD_ETC = "/etc/speech-dispatcher"
MODULE_CONF = os.path.join(SPD_ETC, "modules", f"{MODULE_NAME}.conf")
SPEECHD_CONF = os.path.join(SPD_ETC, "speechd.conf")

# Everything this script adds to speechd.conf lives between these markers, so
# uninstall can remove exactly its own lines and nothing else. Same rule as the
# config.txt installers: never touch a line you did not write.
BEGIN = "# BEGIN OASIS piper"
END = "# END OASIS piper"

# platform.machine() → the UPSTREAM asset arch (not Debian's arm64/armhf).
_ARCH_MAP = {"aarch64": "aarch64", "arm64": "aarch64",
             "armv7l": "armv7l", "armv6l": "armv7l",
             "x86_64": "x86_64", "amd64": "x86_64"}


def _bundle_dir():
    return M.bundle_dir(os.path.join(REPO_ROOT, "offline-packages"), FEATURE)


def _sudo_write(path, body, mode="644"):
    """Write *body* to a root-owned *path* via sudo tee."""
    os.makedirs("/tmp", exist_ok=True)
    tmp = os.path.join("/tmp", f".oasis-piper-{os.path.basename(path)}")
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(body)
    rc = _run(["sudo", "cp", tmp, path], check=False)
    os.remove(tmp)
    if rc.returncode != 0:
        return False
    _run(["sudo", "chmod", mode, path], check=False)
    return True


def _module_conf(piper_bin, model, sample_rate):
    """speech-dispatcher generic-module config.

    GenericExecuteSynth is run by /bin/sh with $DATA holding the text. piper
    writes headerless PCM on stdout (--output_raw), so aplay is told the format
    explicitly — the rate comes from the voice's own .onnx.json rather than being
    assumed, because it differs between voice qualities and a wrong rate plays
    the alert at the wrong pitch and speed.

    `nice` matters on a Pi: inference is multi-threaded and briefly uses every
    core, and an un-niced burst is exactly the kind of spike that arms the load
    guardian.
    """
    return f"""# {MODULE_NAME}.conf — generated by services/satellites/install-piper.py
# Piper neural voice for the OASIS satellite pass alert. Regenerated on every
# install; hand edits are lost. Remove with: install-piper.py --uninstall

GenericExecuteSynth "printf '%s' \\"$DATA\\" | nice -n 10 {piper_bin} \\
    --model {model} --output_raw 2>/dev/null | \\
    aplay -q -r {sample_rate} -f S16_LE -t raw -"

GenericCmdDependency "aplay"
GenericCmdDependency "{piper_bin}"

# The name Chromium shows. It contains "piper" deliberately: the voice ladder in
# common/js/sat-alerts.js prefers a voice whose name contains piper/jenny, and a
# rename here silently drops the box back to espeak with nothing going red.
AddVoice "en" "FEMALE1" "jenny-piper"
DefaultVoice "jenny-piper"

GenericPunctNone ""
GenericPunctSome "--punct=\\"()<>[]{{}}\\""
GenericPunctAll "--punct"

DefaultVolume 100
"""


def _speechd_block():
    return (f"{BEGIN}\n"
            f'AddModule "{MODULE_NAME}" "sd_generic" "{MODULE_NAME}.conf"\n'
            f"{END}\n")


def _strip_block(text):
    """Remove a previously written OASIS block, leaving everything else intact."""
    out, skipping = [], False
    for line in text.splitlines(keepends=True):
        if line.strip() == BEGIN:
            skipping = True
            continue
        if line.strip() == END:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return "".join(out)


def _register_module():
    """Add the AddModule line to speechd.conf, replacing any earlier OASIS block."""
    try:
        with open(SPEECHD_CONF, encoding="utf-8", errors="replace") as f:
            existing = f.read()
    except FileNotFoundError:
        _warn(f"{SPEECHD_CONF} not found — is speech-dispatcher installed? "
              "Run services/satellites/install-voice.py first.")
        return False
    body = _strip_block(existing).rstrip("\n") + "\n\n" + _speechd_block()
    return _sudo_write(SPEECHD_CONF, body)


def _find_engine(bundle):
    arch = _ARCH_MAP.get(platform.machine())
    if not arch:
        return None, None
    feat = M.get_feature(FEATURE)
    asset = feat["asset_pattern"].format(arch=arch, version=feat.get("version"))
    path = os.path.join(bundle, asset)
    return (path, arch) if os.path.exists(path) else (None, arch)


def _find_voice(bundle):
    """(model_path, sample_rate) for the bundled voice, or (None, None).

    Both files are required: piper will not load an .onnx without its .onnx.json,
    and this box has no internet to fetch the missing half.
    """
    vf = M.get_feature(VOICE_FEATURE)
    voice = vf["voice"]
    onnx = os.path.join(bundle, f"{voice}.onnx")
    conf = os.path.join(bundle, f"{voice}.onnx.json")
    if not (os.path.exists(onnx) and os.path.exists(conf)):
        return None, None
    try:
        with open(conf, encoding="utf-8") as f:
            rate = int(json.load(f).get("audio", {}).get("sample_rate", 22050))
    except Exception:
        rate = 22050
    return onnx, rate


def cmd_uninstall():
    _hr()
    print("  ▶  Removing the Piper pass-alert voice")
    _hr()
    if os.path.exists(MODULE_CONF):
        _run(["sudo", "rm", "-f", MODULE_CONF], check=False)
        _ok(f"Removed {MODULE_CONF}")
    try:
        with open(SPEECHD_CONF, encoding="utf-8", errors="replace") as f:
            body = _strip_block(f.read())
        _sudo_write(SPEECHD_CONF, body)
        _ok("Deregistered the module from speechd.conf")
    except FileNotFoundError:
        pass
    if os.path.isdir(INSTALL_DIR):
        _run(["sudo", "rm", "-rf", INSTALL_DIR], check=False)
        _ok(f"Removed {INSTALL_DIR}")
    _info("Pass alerts still speak — the voice ladder falls back to espeak +Steph2.")
    return 0


def run():
    _hr()
    print("  ▶  Satellite pass-alert voice — Piper (neural)")
    _hr()
    if sys.platform != "linux":
        _warn("Not Linux — Piper needs a Pi/Debian speech-dispatcher stack. Nothing to do.")
        return 0

    bundle = _bundle_dir()
    engine, arch = _find_engine(bundle)
    if arch is None:
        _warn(f"Unsupported architecture {platform.machine()} — skipping.")
        return 0
    if engine is None:
        # Not an error: Piper is opt-in, and a bundle built without it is a
        # perfectly good bundle. Say plainly what is missing and how to get it.
        _warn(f"No Piper engine in the bundle for {arch}.")
        _info(f"Expected: {os.path.relpath(bundle, REPO_ROOT)}/")
        _info("Rebuild the offline bundle on a connected machine "
              "(scripts/create-oasis-offline.py) to include it.")
        _info("Pass alerts still speak, using espeak +Steph2.")
        return 0

    model, rate = _find_voice(bundle)
    if model is None:
        _warn("No ONNX voice in the bundle (or it is missing its .onnx.json sidecar).")
        _info("Piper will not load a half voice. Pass alerts fall back to espeak +Steph2.")
        return 0

    _info(f"Engine : {os.path.basename(engine)}")
    _info(f"Voice  : {os.path.basename(model)}  ({rate} Hz)")

    _run(["sudo", "mkdir", "-p", INSTALL_DIR], check=False)
    piper_bin = os.path.join(INSTALL_DIR, "piper", "piper")
    if os.path.exists(piper_bin):
        _ok("Engine already installed — leaving it alone.")
    else:
        # Extracted to a staging dir first, then moved with sudo: tarfile cannot
        # write into a root-owned /opt as the login user.
        staging = os.path.join("/tmp", "oasis-piper-stage")
        shutil.rmtree(staging, ignore_errors=True)
        os.makedirs(staging, exist_ok=True)
        try:
            with tarfile.open(engine) as tf:
                tf.extractall(staging)     # noqa: S202 — our own pinned release asset
        except Exception as e:
            _warn(f"Could not extract {os.path.basename(engine)}: {e}")
            return 0
        _run(["sudo", "cp", "-r", os.path.join(staging, "piper"), INSTALL_DIR], check=False)
        shutil.rmtree(staging, ignore_errors=True)
        if not os.path.exists(piper_bin):
            _warn(f"Engine did not land at {piper_bin} — skipping.")
            return 0
        _ok(f"Engine installed at {piper_bin}")

    dest_model = os.path.join(INSTALL_DIR, os.path.basename(model))
    for src in (model, model + ".json"):
        _run(["sudo", "cp", src, INSTALL_DIR], check=False)
    _run(["sudo", "chmod", "-R", "a+rX", INSTALL_DIR], check=False)
    _ok(f"Voice installed at {dest_model}")

    if not _sudo_write(MODULE_CONF, _module_conf(piper_bin, dest_model, rate)):
        _warn(f"Could not write {MODULE_CONF} — need sudo.")
        return 0
    _ok(f"Wrote {MODULE_CONF}")

    if not _register_module():
        return 0
    _ok("Registered the module in speechd.conf")

    _info("Restart speech-dispatcher and the browser to pick it up:")
    _info("  pkill -u $USER speech-dispatcher   # it respawns on demand")
    _info("Verify:  spd-say -o oasis-piper 'pass alert test'")
    _info("In the kiosk console, the voice ladder should now choose it:")
    _info("  oasisSatPickVoice(speechSynthesis.getVoices()).name")
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="Install the optional Piper neural voice for satellite pass alerts.")
    ap.add_argument("--uninstall", action="store_true",
                    help="Remove the module, its config, and the installed engine/voice.")
    args = ap.parse_args()
    return cmd_uninstall() if args.uninstall else run()


if __name__ == "__main__":
    sys.exit(main())
