"""
gpsd_chrony.py — shared gpsd + chrony ("GPS-disciplined time") setup logic.

Wires a GPS/GNSS serial device into gpsd, then adds the chrony SHM refclock
(+ PPS if /dev/pps0 exists) that actually STEERS the system clock from it —
NO internet needed, and needed for correct FT8/FT4/WSPR/SSTV decode windows,
trustworthy spot timestamps in OpenWebRX, and a sane clock suite-wide.

Used by any feature that has a GPS device to offer:
  - features/gps          (generic USB GPS dongle — ttyACM0/ttyUSB0/...)
  - features/gps-L76X      (Waveshare L76X GPIO/UART GPS HAT — ttyS0/serial0)

gpsd/chrony can only be disciplined by ONE GPS device at a time (a single
DEVICES= line, a single refclock) — these features are mutually exclusive.
Use check_exclusive() before configure_gpsd() to guard against one feature
silently clobbering the device the other one wired up.
"""

import os
import tempfile

from common.oasis_lib import _ok, _info, _warn, _fail, _run, sudo_apt_cmd

GPSD_DEFAULT = "/etc/default/gpsd"
CHRONY_CONF  = "/etc/chrony/chrony.conf"
CHRONY_MARK  = "# OASIS GPS refclock (added by common/gpsd_chrony.py)"
PACKAGES     = ["gpsd", "gpsd-clients", "python3-gps", "chrony"]


def install_packages():
    _run(sudo_apt_cmd("apt", "update", "-qq"), check=False)
    if _run(sudo_apt_cmd("apt", "install", "-y", *PACKAGES), check=False).returncode != 0:
        _fail("apt could not install the GPS/chrony packages "
              "(check internet / apt cache, or a wedged dpkg: sudo dpkg --configure -a).")
    _ok("Installed: " + ", ".join(PACKAGES))


def _sudo_write(path, content, append=False):
    fd, tmp = tempfile.mkstemp()
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
        redir = "tee -a" if append else "tee"
        return _run(["bash", "-c", f"sudo {redir} {path} < {tmp} >/dev/null"],
                    check=False).returncode == 0
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def configured_device():
    """The DEVICES= value currently written to GPSD_DEFAULT, or None (not
    configured yet / unreadable). Used by check_exclusive()."""
    if not os.path.exists(GPSD_DEFAULT):
        return None
    try:
        with open(GPSD_DEFAULT, encoding="utf-8", errors="ignore") as fh:
            content = fh.read()
    except (PermissionError, OSError):
        r = _run(["sudo", "cat", GPSD_DEFAULT], check=False, capture_output=True, text=True)
        content = getattr(r, "stdout", "") or ""
    for line in content.splitlines():
        s = line.strip()
        if s.startswith("DEVICES="):
            return s.split("=", 1)[1].strip().strip('"')
    return None


def check_exclusive(new_device, force=False):
    """gpsd/chrony can only be steered by one GPS device at a time — features/gps
    and features/gps-L76X are mutually exclusive alternatives, not additive.
    Returns True if it's safe to (re)configure gpsd for `new_device`; warns and
    returns False if gpsd is already pointed at a *different* device (unless
    force=True)."""
    existing = configured_device()
    if not existing or existing == new_device or force:
        return True
    _warn(f"gpsd is already configured for {existing} — a different GPS feature "
          "set that up. features/gps and features/gps-L76X are mutually exclusive "
          "(only one GPS device can discipline the clock at a time).")
    _warn(f"Re-run with --force to switch gpsd/chrony over to {new_device}.")
    return False


def configure_gpsd(device):
    content = (
        "# Generated by OASIS (common/gpsd_chrony.py)\n"
        'START_DAEMON="true"\n'
        'USBAUTO="true"\n'
        f'DEVICES="{device}"\n'
        'GPSD_OPTIONS="-n"\n'   # -n: poll the GPS even with no client, so chrony's SHM stays fed
    )
    if _sudo_write(GPSD_DEFAULT, content):
        _ok(f"Wrote {GPSD_DEFAULT} (DEVICES={device}, GPSD_OPTIONS=-n).")
    else:
        _fail(f"Could not write {GPSD_DEFAULT}.")


def configure_chrony():
    if not os.path.exists(CHRONY_CONF):
        _warn(f"{CHRONY_CONF} not found — is chrony installed? Skipping refclock.")
        return
    already = _run(["bash", "-c", f"sudo grep -qF '{CHRONY_MARK}' {CHRONY_CONF}"],
                   check=False).returncode == 0
    if already:
        _ok("chrony already has the OASIS GPS refclock — leaving it.")
        return
    lines = [CHRONY_MARK,
             "refclock SHM 0 refid GPS precision 1e-1 offset 0.0 delay 0.2"]
    # PPS via gpsd's SHM segment 1, NOT the raw /dev/pps0 device. A raw
    # `refclock PPS /dev/pps0` is a *fatal* chronyd error when the node is
    # missing, and with pps_ldisc the node only appears after gpsd attaches it —
    # so at boot chrony starts first and dies (works only on a later manual
    # restart). An SHM refclock never fatally fails: gpsd (which owns the PPS)
    # relays it on SHM 1, and until that's ready chrony simply gets no PPS
    # samples and runs on SHM 0. /dev/pps0 here is only a "this box has PPS" hint.
    if os.path.exists("/dev/pps0"):
        lines.append("refclock SHM 1 refid PPS precision 1e-7 lock GPS")
        _info("PPS device found — adding a gpsd-SHM PPS refclock (boot-safe).")
    if _sudo_write(CHRONY_CONF, "\n" + "\n".join(lines) + "\n", append=True):
        _ok("Added GPS refclock to chrony.conf (the step most setups miss).")
    else:
        _fail(f"Could not append the refclock to {CHRONY_CONF}.")


def restart_services():
    for unit in ("gpsd.socket", "gpsd", "chrony", "chronyd"):
        _run(["sudo", "systemctl", "enable", unit], check=False)
    for unit in ("gpsd", "chrony", "chronyd"):
        _run(["sudo", "systemctl", "restart", unit], check=False)
    _ok("Enabled + restarted gpsd and chrony.")


def verify():
    gpsd_ok = _run(["systemctl", "is-active", "--quiet", "gpsd"], check=False).returncode == 0
    _ok("gpsd active.") if gpsd_ok else _warn("gpsd is not active.")
    src = _run(["chronyc", "sources"], check=False, capture_output=True, text=True)
    out = getattr(src, "stdout", "") or ""
    if "GPS" in out:
        _ok("chrony lists the GPS refclock.")
    else:
        _warn("chrony does not list a GPS source yet — needs a fix + ~1 min.")
    _info("Confirm a fix:  cgps -s        (look for 3D FIX)")
    _info("Confirm time :  chronyc sources -v   then   chronyc tracking")
