#!/usr/bin/env python3
"""Build static/js/adsb-operators.js from OpenFlights airlines.dat.

Offline build step: download airlines.dat once (OpenFlights raw data,
data/airlines.dat in https://github.com/jpatokal/openflights) and pass its
path. Emits ICAO(3-letter) -> ATC telephony callsign. The generated table is
committed; the raw source is not (gitignored).
"""
import argparse
import csv
import json
import os
import sys

HEADER = ("/* Generated by scripts/build-adsb-operators.py -- do not edit by hand.\n"
          "   Source: OpenFlights airlines.dat (Open Database License).\n"
          "   ICAO 3-letter -> ATC telephony callsign. */\n")


def build(src):
    ops = {}
    with open(src, newline="", encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) < 8:
                continue
            icao = (row[4] or "").strip().upper()
            callsign = (row[5] or "").strip().upper()
            active = (row[7] or "").strip().upper()
            if len(icao) != 3 or not icao.isalpha():
                continue
            if not callsign or callsign == "\\N":
                continue
            # Prefer active carriers: never overwrite an already-recorded active
            # entry; a later active does replace an earlier inactive one.
            if icao in ops and ops[icao][1] == "Y":
                continue
            ops[icao] = (callsign, active)
    return {k: v[0] for k, v in sorted(ops.items())}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", default="scripts/data/airlines.dat",
                    help="path to OpenFlights airlines.dat (download once; gitignored)")
    ap.add_argument("--out", default="static/js/adsb-operators.js")
    args = ap.parse_args()
    if not os.path.exists(args.src):
        sys.exit(f"source not found: {args.src} -- download OpenFlights airlines.dat there first")
    ops = build(args.src)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("globalThis.OASIS_OPERATORS = "
                + json.dumps(ops, ensure_ascii=False, sort_keys=True) + ";\n")
    print(f"wrote {args.out}: {len(ops)} operators")


if __name__ == "__main__":
    main()
