#!/usr/bin/env python3
"""
enable-service-controls.py
--------------------------
Grant the OASIS server's user permission to start / stop / restart the OASIS
services from the dashboard power buttons — WITHOUT any password ever touching
the web layer.

It installs a narrow, validated `sudoers` rule (/etc/sudoers.d/oasis-service-
controls) that allows ONLY `systemctl start|stop|restart|enable|disable <unit>.service` for the
known OASIS units below, plus one fixed read-only `tcpdump -ni lo … udp port 7355`
for the dashboard's APRS SDR feed flow meter (/api/health/feed-flow), and nothing
else. The endpoints then run `sudo -n …`; the OS authorizes the exact command, so
OASIS never handles a credential.

Notably absent from the list: the `oasis` service itself — stopping the web
server would kill the dashboard with no way to bring it back from the browser.

Opt-in and reversible. Run as your normal user (it asks for sudo once to write
the file); it refuses to run on non-Linux.

Usage:
  python3 scripts/enable-service-controls.py            # grant (current user)
  python3 scripts/enable-service-controls.py --user pi  # grant for a specific user
  python3 scripts/enable-service-controls.py --check    # report status
  python3 scripts/enable-service-controls.py --disable  # remove the permission

Requires: Linux, systemd, sudo.
"""

import argparse
import getpass
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common.oasis_lib import _hr, _step, _ok, _info, _warn, _fail, _run

# Must match server/app.py _CONTROLLABLE_SERVICES (everything OASIS-managed
# except the web server itself).
UNITS   = ["graywolf", "graywolf-api", "pat", "kiwix", "webssh",
           "aprs-sdr-feed", "openwebrx"]
# enable/disable included so boot-state-tracking units (e.g. OpenWebRX: enable on
# start, disable on stop) work; the dashboard still only exposes start/stop/restart.
ACTIONS = ["start", "stop", "restart", "enable", "disable"]
SUDOERS_PATH = "/etc/sudoers.d/oasis-service-controls"

# Passive RTL-SDR → GrayWolf feed flow probe (dashboard "APRS SDR Feed" meter).
# These MUST match server/app.py's _FEED_FLOW_ARGS / FEED_FLOW_PORT token-for-
# token — the endpoint runs `sudo -n <tcpdump> <SNIFF_ARGS>` and sudo only
# authorizes an exact command match. tcpdump on lo just *reads* a copy of the
# feed datagrams; it can't transmit or touch any other interface.
FEED_FLOW_PORT = 7355
SNIFF_ARGS = ["-ni", "lo", "-l", "-c", "10", "udp", "port", str(FEED_FLOW_PORT)]


def target_user(explicit):
    """User the OASIS server runs as: explicit > $SUDO_USER > current user."""
    return explicit or os.environ.get("SUDO_USER") or getpass.getuser()


def build_content(user, systemctl, tcpdump):
    cmds = ", ".join(f"{systemctl} {a} {u}.service" for u in UNITS for a in ACTIONS)
    sniff = tcpdump + " " + " ".join(SNIFF_ARGS)
    return (
        "# OASIS dashboard service controls — generated by enable-service-controls.py\n"
        f"# Lets '{user}' start/stop/restart only these OASIS units, no password,\n"
        f"# plus a fixed read-only tcpdump on lo for the APRS SDR feed flow meter.\n"
        f"Cmnd_Alias OASIS_SVC = {cmds}\n"
        f"Cmnd_Alias OASIS_SNIFF = {sniff}\n"
        f"{user} ALL=(root) NOPASSWD: OASIS_SVC, OASIS_SNIFF\n"
    )


def install(user):
    systemctl = shutil.which("systemctl") or "/usr/bin/systemctl"
    tcpdump   = shutil.which("tcpdump")   or "/usr/bin/tcpdump"
    content   = build_content(user, systemctl, tcpdump)
    _info(f"systemctl: {systemctl}")
    _info(f"tcpdump:   {tcpdump}  (read-only feed flow probe on lo)")
    _info("Units: " + ", ".join(UNITS))

    # Write to a temp file, VALIDATE with visudo, then install atomically. A
    # malformed sudoers file can lock you out of sudo, so we never write it
    # directly — visudo -cf must pass first.
    fd, tmp = tempfile.mkstemp(suffix=".sudoers")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
        if _run(["sudo", "visudo", "-cf", tmp], check=False).returncode != 0:
            _fail("Generated sudoers file failed validation — NOT installing.")
        if _run(["sudo", "install", "-m", "0440", "-o", "root", "-g", "root",
                 tmp, SUDOERS_PATH], check=False).returncode != 0:
            _fail(f"Could not install {SUDOERS_PATH} (sudo required).")
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass
    _ok(f"Installed {SUDOERS_PATH} for user '{user}'.")


def disable():
    if not os.path.exists(SUDOERS_PATH):
        _ok("Already disabled (no sudoers file present).")
        return
    if _run(["sudo", "rm", "-f", SUDOERS_PATH], check=False).returncode == 0:
        _ok(f"Removed {SUDOERS_PATH}.")
    else:
        _fail(f"Could not remove {SUDOERS_PATH} (sudo required).")


def status():
    present = os.path.exists(SUDOERS_PATH)
    _info(f"sudoers file: {'present' if present else 'absent'}  ({SUDOERS_PATH})")
    r = _run(["sudo", "-n", "-l"], check=False, capture_output=True, text=True)
    out = getattr(r, "stdout", "") or ""
    if r.returncode == 0 and "OASIS_SVC" in out:
        _ok("sudo grants the OASIS service commands without a password.")
    else:
        _warn("sudo does not grant the OASIS service commands NOPASSWD for this user yet.")
    if r.returncode == 0 and ("OASIS_SNIFF" in out or "tcpdump" in out):
        _ok("sudo grants the feed flow probe (tcpdump on lo) without a password.")
    else:
        _warn("sudo does not grant the feed flow probe yet — the APRS SDR Feed meter "
              "will show 'flow: enable controls'. Re-run without --check to grant it.")


def run(args):
    print("\n  OASIS — enable-service-controls")
    _hr()
    if sys.platform != "linux":
        _fail("Service controls use systemd + sudoers — Linux only.")

    if args.check:
        status()
        print()
        return

    if args.disable:
        _step(1, "Removing dashboard service-control permission")
        disable()
        print()
        return

    user = target_user(args.user)
    _step(1, f"Granting '{user}' scoped NOPASSWD systemctl for OASIS units")
    install(user)
    _info("The dashboard power buttons (start / stop) will now work.")
    _info("Undo with: python3 scripts/enable-service-controls.py --disable")
    print()


def main():
    ap = argparse.ArgumentParser(
        description="Allow the OASIS user to start/stop/restart OASIS services "
                    "from the dashboard (scoped sudoers NOPASSWD — no passwords in the browser).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=("Examples:\n"
                "  python3 scripts/enable-service-controls.py            # grant (current user)\n"
                "  python3 scripts/enable-service-controls.py --user pi  # grant for 'pi'\n"
                "  python3 scripts/enable-service-controls.py --check     # report status\n"
                "  python3 scripts/enable-service-controls.py --disable   # remove\n"),
    )
    ap.add_argument("--user", help="User the OASIS server runs as (default: $SUDO_USER or current user).")
    ap.add_argument("--disable", action="store_true", help="Remove the permission.")
    ap.add_argument("--check", action="store_true", help="Report whether the permission is installed.")
    run(ap.parse_args())


if __name__ == "__main__":
    main()
