#!/usr/bin/env python3
"""
install-rtl-sdr.py
------------------
Install RTL-SDR tools and kernel module blacklist on Raspberry Pi OS or any
Debian/Ubuntu Linux system.

What this does:
  1. Detects your architecture and Debian suite (bookworm / bullseye)
  2. Installs: rtl-sdr, librtlsdr2 (or librtlsdr0), libusb-1.0-0
     from offline-packages/rtl-sdr/ if bundled packages are present,
     otherwise falls back to apt (internet required)
  3. Installs the feed tools socat + tcpdump (same offline-first / apt logic) —
     socat carries the SDR audio into GrayWolf; tcpdump verifies it. Pi OS ships
     with neither. Used by enable-rtl-sdr.py.
  4. Blacklists the dvb_usb_rtl28xxu kernel module that conflicts with RTL-SDR
  5. Verifies the install with rtl_test --help

After install, plug in your RTL-SDR dongle and run:
  rtl_test -t            # verify device is found
  rtl_fm -f 144.390M ... # receive APRS/FM audio
  python3 scripts/enable-rtl-sdr.py   # wire the dongle into GrayWolf (RX-only)

Supported hardware: RTL2832U-based USB dongles (RTL-SDR Blog V3/V4, Nooelec, etc.)

Install source is chosen automatically: bundled .deb packages in
offline-packages/rtl-sdr/ are used when present (fully offline); otherwise
apt is used (internet required). If a package can't be installed, the error
is logged and the script continues with the remaining steps.

Usage:
  python3 scripts/install-rtl-sdr.py

Requires: Linux, apt/dpkg, sudo. Internet optional if bundled packages present.
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys

# ── Shared library ─────────────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common.oasis_lib import (
    _hr, _step, _ok, _info, _warn, _fail, _run,
    deb_field, dpkg_installed_version, version_decision,
)

REPO_ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OFFLINE_DIR = os.path.join(REPO_ROOT, "offline-packages", "rtl-sdr")

# Blacklist file — prevents the generic DVB driver from grabbing the dongle.
BLACKLIST_FILE = "/etc/modprobe.d/rtlsdr-blacklist.conf"
BLACKLIST_CONTENT = """\
# RTL-SDR: prevent the generic DVB driver from claiming the dongle.
# Generated by OASIS install-rtl-sdr.py
blacklist dvb_usb_rtl28xxu
blacklist rtl2832
blacklist rtl2830
"""




# ── Step 1: Platform check ─────────────────────────────────────────────────────
def check_platform():
    _step(1, "Checking platform")

    if sys.platform != "linux":
        _fail("RTL-SDR Debian packages require a Linux system.\n"
              "       On macOS: brew install librtlsdr\n"
              "       On Windows: use Zadig to install WinUSB, then install SDR# or HDSDR.")

    if _run(["which", "apt"], check=False, capture_output=True).returncode != 0:
        _fail("apt not found. This script supports Debian/Ubuntu/Raspberry Pi OS.\n"
              "       For Fedora/RHEL: sudo dnf install rtl-sdr\n"
              "       For Arch: sudo pacman -S rtl-sdr")

    machine = platform.machine()
    _info(f"Architecture: {machine}")

    arch_map = {
        "aarch64": "arm64",   # Pi Zero 2W, Pi 3/4/5 (64-bit OS)
        "arm64":   "arm64",
        "armv7l":  "armhf",   # Pi 2/3/4 (32-bit OS)
        "armhf":   "armhf",
        "armv6l":  "armhf",   # Pi 1 / Pi Zero — closest available
        "x86_64":  "amd64",
        "amd64":   "amd64",
    }
    deb_arch = arch_map.get(machine)
    if not deb_arch:
        _fail(f"No RTL-SDR package available for architecture '{machine}'.")

    _ok("Debian/apt-based Linux detected")
    _ok(f"Architecture → .deb arch: {deb_arch}")
    return deb_arch


# ── Step 2: Detect Debian suite ───────────────────────────────────────────────
def detect_suite():
    """Return 'bookworm', 'bullseye', or 'other'."""
    try:
        result = subprocess.run(
            ["lsb_release", "-cs"], capture_output=True, text=True, check=True
        )
        suite = result.stdout.strip().lower()
    except Exception:
        suite = "other"

    # Map Ubuntu LTS codenames to their Debian equivalent for package naming.
    ubuntu_to_debian = {
        "jammy": "bookworm",
        "focal": "bullseye",
        "noble": "bookworm",
    }
    suite = ubuntu_to_debian.get(suite, suite)

    _info(f"Debian suite: {suite}")
    return suite


# ── Step 3: Find local .deb packages ─────────────────────────────────────────
# Required packages. The librtlsdr runtime was renamed across Debian releases
# (librtlsdr0 in bullseye/bookworm, librtlsdr2 in trixie/sid), so accept either.
REQUIRED_DEBS = {
    "rtl-sdr":      ["rtl-sdr_"],
    "libusb-1.0-0": ["libusb-1.0-0_"],
    "librtlsdr":    ["librtlsdr0_", "librtlsdr2_"],
}

# Feed tools for the RTL-SDR → GrayWolf sdr_udp path (see enable-rtl-sdr.py and
# docs/sdr-to-graywolf.md). socat carries the audio; tcpdump verifies it. Their
# not-always-present shared-lib deps are bundled so the offline install resolves.
FEED_DEBS = {
    "socat":      ["socat_"],
    "tcpdump":    ["tcpdump_"],
    "libwrap0":   ["libwrap0_"],
    "libpcap0.8": ["libpcap0.8_"],
}


def find_local_debs(deb_arch, required=REQUIRED_DEBS):
    """
    Scan offline-packages/rtl-sdr/ for the *required* .debs matching deb_arch.
    Returns (deb_paths, missing) where missing names the required packages not
    found. macOS AppleDouble sidecars (._*) are ignored.
    """
    found = {}
    if os.path.isdir(OFFLINE_DIR):
        for fname in sorted(os.listdir(OFFLINE_DIR)):
            if fname.startswith("._") or not fname.endswith(f"_{deb_arch}.deb"):
                continue
            for key, prefixes in required.items():
                if key not in found and any(fname.startswith(p) for p in prefixes):
                    found[key] = os.path.join(OFFLINE_DIR, fname)

    missing = [k for k in required if k not in found]
    return list(found.values()), missing


# ── Step 4: Install RTL-SDR (best-effort) ─────────────────────────────────────
def install_offline(deb_paths, label="RTL-SDR"):
    """Install bundled .debs, but never downgrade an already-newer package.

    For each .deb we compare its version to what's installed and only install
    the ones that are absent or newer — so a stale bundled package can't
    clobber a newer one already on the system.
    """
    to_install = []
    for p in deb_paths:
        pkg  = deb_field(p, "Package") or os.path.basename(p)
        ourv = deb_field(p, "Version")
        inst = dpkg_installed_version(pkg)
        if version_decision(pkg, ourv, inst) in ("install", "upgrade"):
            to_install.append(p)

    if not to_install:
        _ok(f"All {label} packages already current — nothing to install.")
        return True

    _info("Installing:")
    for p in to_install:
        _info(f"  {os.path.basename(p)}")

    # apt install ./file.deb resolves local deps from the bundled set.
    cmd = ["sudo", "apt", "install", "--no-install-recommends", "-y"] + to_install
    if _run(cmd, check=False).returncode == 0:
        _ok("Packages installed via apt")
        return True
    _warn("Offline install failed. If you saw dependency errors, try:")
    _warn("  sudo apt-get install -f")
    return False


def install_online():
    """Install rtl-sdr from apt. Returns True on success, else False."""
    _info("Installing via apt (internet) ...")
    _run(["sudo", "apt", "update", "-qq"], check=False)
    if _run(["sudo", "apt", "install", "-y", "rtl-sdr"], check=False).returncode == 0:
        _ok("rtl-sdr installed")
        return True
    _warn("apt could not install rtl-sdr.")
    return False


def _report_incomplete(deb_paths, missing):
    _warn(f"Offline package set in {os.path.relpath(OFFLINE_DIR)}/ is incomplete.")
    if deb_paths:
        _info("Present: " + ", ".join(os.path.basename(p) for p in deb_paths))
    _warn("Missing: " + ", ".join(missing))
    _info("Re-fetch with: python3 scripts/create-oasis-offline.py")


def install_rtl_sdr(deb_paths, missing):
    """Install RTL-SDR: local .debs first, fall back to apt, log and continue."""
    _step(4, "Installing RTL-SDR tools")

    complete  = deb_paths and not missing
    installed = False

    if complete:
        _info("Bundled packages found — installing offline.")
        installed = install_offline(deb_paths)
        if not installed:
            _warn("Offline install failed — falling back to apt.")
            installed = install_online()
    else:
        if deb_paths or missing:
            _report_incomplete(deb_paths, missing)
        _info("No complete offline set — trying apt (requires internet) ...")
        installed = install_online()

    if not installed:
        _fail(
            "RTL-SDR tools could not be installed from offline packages or apt.\n"
            "       Check the errors above. If packages are missing, rebuild the bundle:\n"
            "         python3 scripts/create-oasis-offline.py"
        )
    return installed


# ── Step 5: Feed tools (socat, tcpdump) ──────────────────────────────────────
def install_feed_online(missing):
    """apt-install the missing feed tools (deps resolved online). Returns bool."""
    _info("Installing feed tools via apt (internet) ...")
    _run(["sudo", "apt", "update", "-qq"], check=False)
    if _run(["sudo", "apt", "install", "-y", *missing], check=False).returncode == 0:
        _ok("Feed tools installed via apt")
        return True
    _warn("apt could not install the feed tools.")
    return False


def install_feed_tools(deb_arch):
    """Install socat + tcpdump for the GrayWolf feed: bundled .debs first, then
    apt. Best-effort — logs and continues; socat is what the feed actually needs.
    """
    _step(5, "Installing feed tools (socat, tcpdump)")

    have = {p: shutil.which(p) is not None for p in ("socat", "tcpdump")}
    if all(have.values()):
        _ok("socat and tcpdump already installed.")
        return
    missing = [p for p, ok in have.items() if not ok]
    _info("Missing: " + ", ".join(missing))

    feed_paths, feed_missing = find_local_debs(deb_arch, FEED_DEBS)
    installed = False
    if feed_paths and not feed_missing:
        _info("Bundled feed packages found — installing offline.")
        installed = install_offline(feed_paths, label="feed-tool")
        if not installed:
            _warn("Offline feed install failed — falling back to apt.")
    elif feed_paths or feed_missing:
        _report_incomplete(feed_paths, feed_missing)

    if not installed:
        installed = install_feed_online(missing)

    if not installed:
        _warn("Could not install socat/tcpdump. The RTL-SDR → GrayWolf audio "
              "feed needs socat. Install manually:")
        _warn("  sudo apt install -y socat tcpdump")
        return

    still = [p for p in ("socat", "tcpdump") if shutil.which(p) is None]
    if still:
        _warn("Still missing after install: " + ", ".join(still))
    else:
        _ok("Feed tools ready — socat (feed) + tcpdump (verification).")


# ── Step 6: Blacklist the conflicting DVB kernel module ──────────────────────
def blacklist_dvb():
    _step(6, "Blacklisting DVB kernel module")
    _info(f"Writing {BLACKLIST_FILE}")

    try:
        result = subprocess.run(
            ["sudo", "tee", BLACKLIST_FILE],
            input=BLACKLIST_CONTENT,
            text=True,
            capture_output=True,
        )
        if result.returncode != 0:
            _warn(f"Could not write blacklist: {result.stderr.strip()}")
            return
        _ok("dvb_usb_rtl28xxu, rtl2832, rtl2830 blacklisted")
    except Exception as exc:
        _warn(f"Blacklist step failed: {exc}")
        return

    # Unload the module if currently loaded.
    for mod in ("dvb_usb_rtl28xxu", "rtl2832", "rtl2830"):
        unload = subprocess.run(
            ["sudo", "modprobe", "-r", mod], capture_output=True
        )
        if unload.returncode == 0:
            _info(f"Unloaded module: {mod}")

    _info("Reboot for the blacklist to take full effect on next plug-in.")


# ── Step 7: Verify install ─────────────────────────────────────────────────────
def verify():
    _step(7, "Verifying install")
    result = subprocess.run(
        ["rtl_test", "--help"], capture_output=True, text=True
    )
    # rtl_test --help exits non-zero but prints help text.
    if "rtl_test" in result.stdout + result.stderr:
        _ok("rtl_test found and responsive")
    elif _run(["which", "rtl_test"], check=False, capture_output=True).returncode == 0:
        _ok("rtl_test found")
    else:
        _warn("rtl_test not in PATH — the install may have failed.")
        return

    _info("Plug in your RTL-SDR dongle and run:  rtl_test -t")


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Install RTL-SDR tools on Debian/Ubuntu/Raspberry Pi OS.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python3 scripts/install-rtl-sdr.py   # bundled .debs if present, else apt\n"
        ),
    )
    parser.parse_args()

    print("\n  OASIS — install-rtl-sdr")
    _hr()
    _info("Installs RTL-SDR tools for SDR operation on Raspberry Pi.")
    _info("Supported: Pi OS (arm64/armhf), Debian/Ubuntu (amd64).")
    print()

    deb_arch = check_platform()

    _step(2, "Detecting Debian suite")
    detect_suite()

    _step(3, "Looking for offline packages")
    _info(f"Offline dir: {os.path.relpath(OFFLINE_DIR)}")
    deb_paths, missing = find_local_debs(deb_arch)
    if deb_paths and not missing:
        _ok(f"Found complete offline set ({len(deb_paths)} packages) — will install offline")
    elif deb_paths:
        _ok(f"Found {len(deb_paths)} of {len(REQUIRED_DEBS)} required packages (incomplete)")
    else:
        _info("No offline packages found — will use apt.")

    install_rtl_sdr(deb_paths, missing)

    install_feed_tools(deb_arch)
    blacklist_dvb()
    verify()

    _hr()
    print("\n  RTL-SDR install complete.")
    _info("Plug in your dongle and run:  rtl_test -t")
    _info("For APRS receive:  rtl_fm -f 144.390M -M fm -s 48000 - | aplay -r 48000 -f S16_LE -t raw -c 1")
    _info("Wire it into GrayWolf:  python3 scripts/enable-rtl-sdr.py")
    print()


if __name__ == "__main__":
    main()
